version: '2'
services:
  app:
    image: ${REGISTRY_URI}tsgctf-test-crypto:${TAG:-latest}
    build: .
    restart: always
    ports:
      - 65434:65434
    environment:
      TCPDUMP_ENABLE: 'true'
      FLAG: TSGCTF{YOU_ARE_PERFECT_AND_ULTIMATE_HACKER}
      CTF_PORT: 65434
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512MB
        reservations:
          cpus: '0.25'
          memory: 512MB